-- ============================================================
-- TaskMaster — Manual SQL Setup Script
-- Run this in phpMyAdmin or MySQL CLI if needed
-- Laravel migrations do this automatically via:  php artisan migrate
-- ============================================================

-- Create the database
CREATE DATABASE IF NOT EXISTS taskmaster_db
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE taskmaster_db;

-- ── Table 1: users ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    id             BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name           VARCHAR(255)    NOT NULL,
    email          VARCHAR(255)    NOT NULL UNIQUE,
    password       VARCHAR(255)    NOT NULL,
    remember_token VARCHAR(100)    DEFAULT NULL,
    created_at     TIMESTAMP       NULL DEFAULT NULL,
    updated_at     TIMESTAMP       NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── Table 2: categories ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS categories (
    id         BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    color      VARCHAR(20)  NOT NULL DEFAULT '#6366f1',
    created_at TIMESTAMP    NULL DEFAULT NULL,
    updated_at TIMESTAMP    NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── Table 3: tasks ──────────────────────────────────────────
-- This table has TWO foreign keys:
--   user_id     → references users(id)    ON DELETE CASCADE
--   category_id → references categories(id) ON DELETE CASCADE
CREATE TABLE IF NOT EXISTS tasks (
    id          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id     BIGINT UNSIGNED NOT NULL,
    category_id BIGINT UNSIGNED NOT NULL,
    title       VARCHAR(255)    NOT NULL,
    description TEXT            DEFAULT NULL,
    due_date    DATE            NOT NULL,
    priority    ENUM('low','medium','high')              NOT NULL DEFAULT 'medium',
    status      ENUM('pending','in_progress','done')    NOT NULL DEFAULT 'pending',
    created_at  TIMESTAMP       NULL DEFAULT NULL,
    updated_at  TIMESTAMP       NULL DEFAULT NULL,

    -- Foreign key constraints (enforces referential integrity)
    CONSTRAINT fk_tasks_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_tasks_category
        FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── Seed: Default categories ────────────────────────────────
INSERT INTO categories (name, color, created_at, updated_at) VALUES
    ('Mathematics', '#6366f1', NOW(), NOW()),
    ('Science',     '#10b981', NOW(), NOW()),
    ('English',     '#f59e0b', NOW(), NOW()),
    ('History',     '#ef4444', NOW(), NOW()),
    ('Filipino',    '#ec4899', NOW(), NOW()),
    ('Personal',    '#8b5cf6', NOW(), NOW());

-- ── Seed: Demo student account ──────────────────────────────
-- Password is 'password' (bcrypt hash — generated by Laravel)
INSERT INTO users (name, email, password, created_at, updated_at) VALUES
    ('Juan dela Cruz', 'demo@taskmaster.com',
     '$2y$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
     NOW(), NOW());

-- ── Seed: Sample tasks for demo user ────────────────────────
INSERT INTO tasks (user_id, category_id, title, description, due_date, priority, status, created_at, updated_at)
VALUES
    (1, 1, 'Solve Chapter 3 Exercises',  'Pages 45-52, problems 1-20',
        DATE_ADD(CURDATE(), INTERVAL 2 DAY),  'high',   'pending',     NOW(), NOW()),
    (1, 2, 'Lab Report: Photosynthesis', 'Write conclusions for the experiment',
        DATE_ADD(CURDATE(), INTERVAL 5 DAY),  'medium', 'in_progress', NOW(), NOW()),
    (1, 3, 'Book Review: Noli Me Tangere', NULL,
        DATE_ADD(CURDATE(), INTERVAL 7 DAY),  'low',    'done',        NOW(), NOW());

-- ── Sample CRUD queries (for documentation/demo) ─────────────

-- READ: Get all tasks for user 1 with category name (JOIN)
SELECT t.id, t.title, t.due_date, t.priority, t.status,
       c.name AS category, c.color
FROM   tasks t
JOIN   categories c ON t.category_id = c.id
WHERE  t.user_id = 1
ORDER  BY t.due_date ASC;

-- READ: Count tasks by status for dashboard stats
SELECT status, COUNT(*) AS total
FROM   tasks
WHERE  user_id = 1
GROUP  BY status;

-- READ: Get overdue tasks
SELECT title, due_date FROM tasks
WHERE  user_id = 1
AND    status != 'done'
AND    due_date < CURDATE();

-- UPDATE: Change status
-- UPDATE tasks SET status = 'done', updated_at = NOW() WHERE id = 1;

-- DELETE: Remove a task
-- DELETE FROM tasks WHERE id = 1 AND user_id = 1;
